
services:

  loki:
    image: grafana/loki:3.5.6
    restart: unless-stopped
    ports:
      - 3100
    volumes:
      - ./loki/local-config.yaml:/etc/loki/custom-local-config.yaml:ro
      - ../certs:/certs:ro
    command: -config.file=/etc/loki/custom-local-config.yaml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:12.2.0
    restart: unless-stopped
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ../certs:/certs:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    networks:
      - monitoring
    ports:
      - 3000:3000

  otlp:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.137.0
    command: ["--config=/etc/otel-collector-config.yml"]
    restart: unless-stopped
    #extra_hosts: ['host.docker.internal:host-gateway']
    volumes:
    - ./otel/config.yml:/etc/otel-collector-config.yml
    - ../certs:/certs:ro
    ports:
    - "4317:4317"  # otlp gprc (insecure)
    - "4318:4318"  # otlp http (insecure)
    - "4319:4319"  # otlp grpc (tls)
    - "4320:4320"  # otlp grpc (mtls)
    environment:
      TZ: "Europe/Berlin"

    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v3.6.0
    restart: unless-stopped
    environment:
      TZ: "Europe/Berlin"
    volumes:
       - ./prometheus:/etc/prometheus/
       - ../certs:/certs:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.config.file=/etc/prometheus/tls-config.yml'
      - '--web.enable-otlp-receiver'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=exemplar-storage'
      - '--log.level=debug'

    networks:
      - monitoring
    ports:
      - 9090

  tempo:
    image: grafana/tempo:2.8.2
    #extra_hosts: ['host.docker.internal:host-gateway']
    restart: unless-stopped
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
        - ./tempo/tempo-local.yml:/etc/tempo.yml:ro
        - ../certs:/certs:ro
    ports:
      - "4317"
      - "3200"
      - "9095"

    networks:
      - monitoring

networks:
  monitoring:


