x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'
    loki-pipeline-stages: |
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<date>\d{4}-\d{2}-\d{2}) (?P<time>\d{2}:\d{2}:\d{2}.\d{3}) (?P<message>(?s:.*))$$'

version: '3.4'

services:

  loki:
    image: grafana/loki:2.9.2
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:10.2.2
    restart: unless-stopped
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true

    networks:
      - monitoring
    ports:
      - 3300:3000

  otlp:
    image: otel/opentelemetry-collector:0.91.0
    command: [ "--config=/etc/otel-collector-config.yml" ]
    #extra_hosts: ['host.docker.internal:host-gateway']
    volumes:
      - ./otel/config.yml:/etc/otel-collector-config.yml
    ports:
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "9411:9411" # Prometheus exporter metrics
      - "4317:4317" # otlp gprc
      #- "9090:9090"   # Prometheus exporter metrics
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.48.1
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=exemplar-storage'

    networks:
      - monitoring
    ports:
      - 9090:9090

  tempo:
    image: grafana/tempo:2.3.1
    #extra_hosts: ['host.docker.internal:host-gateway']
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./tempo/tempo-local.yml:/etc/tempo.yml:ro
      # - ./tempo-data:/tmp/tempo
    ports:
      - "4317"
      - "3200"
      #- "14268"  # jaeger ingest
      #- "9411:9411" # zipkin
    networks:
      - monitoring

networks:
  monitoring:


