x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'
    loki-pipeline-stages: |
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<date>\d{4}-\d{2}-\d{2}) (?P<time>\d{2}:\d{2}:\d{2}.\d{3}) (?P<message>(?s:.*))$$'



services:

  loki:
    image: grafana/loki:3.5.1
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:12.0.1
    restart: unless-stopped
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    networks:
      - monitoring
    ports:
      - 3000:3000

  otlp:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.127.0
    command: ["--config=/etc/otel-collector-config.yml"]
    restart: unless-stopped
    #extra_hosts: ['host.docker.internal:host-gateway']
    volumes:
    - ./otel/config.yml:/etc/otel-collector-config.yml
    ports:
    - "4317:4317"  # otlp gprc
    - "4318:4318"  # otlp http
    environment:
      TZ: "Europe/Berlin"

    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v3.4.0
    restart: unless-stopped
    environment:
      TZ: "Europe/Berlin"
    # volumes:
    #    - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-otlp-receiver'
      - '--enable-feature=exemplar-storage'
      - '--log.level=debug'

    networks:
      - monitoring
    ports:
      - 9090:9090

  tempo:
    image: grafana/tempo:2.7.2
    #extra_hosts: ['host.docker.internal:host-gateway']
    restart: unless-stopped
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
        - ./tempo/tempo-local.yml:/etc/tempo.yml:ro
        # - ./tempo-data:/tmp/tempo
    ports:
      - "4317"
      - "3200"
      #- "14268"  # jaeger ingest
      #- "9411:9411" # zipkin
    networks:
      - monitoring

networks:
  monitoring:


