receivers:
  # Collect own metrics
  otlp:
    protocols:
      grpc:
        endpoint: otlp:4317 # use service name here
      http:
        endpoint: otlp:4318 # use service name here

processors:
  batch:
  memory_limiter:
    check_interval: 2s
    limit_percentage: 30
    spike_limit_percentage: 10

  attributes/prometheus:
    actions:
      - key: service_version
        action: delete

exporters:
  debug:
    verbosity: detailed

  otlp/tempo:
    endpoint: "tempo:4317"
    tls:
      insecure: true
  otlphttp/loki:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true
  otlphttp/prometheus:
    endpoint: http://prometheus:9090/api/v1/otlp
    tls:
      insecure: true

service:
  telemetry:
    logs:
      level: debug

  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/tempo, debug]

    metrics:
      receivers: [otlp]
      processors: [memory_limiter, attributes/prometheus, batch]
      exporters: [otlphttp/prometheus]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/loki, debug]
