# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
# These datasources are connected to cope with data ingested by the OpenTelemetry collector
# via gRPC to loki, tempo and prometheus
# The otel-collector receives the data completely via gRPC. No scrapers are used for prometheus or loki
# MP 2025-05-04
datasources:
  - uid: loki
    orgId: 1
    name: Loki
    type: loki
    typeName: Loki
    typeLogoUrl: public/app/plugins/datasource/loki/img/loki_icon.svg
    access: proxy
    url: https://loki:3100
    user: ""
    database: ""
    basicAuth: false
    isDefault: false
    jsonData:
      serverName: loki
      tlsAuth: true
      tlsAuthWithCACert: true
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: trace_id
          matcherType: label
          name: trace_id
          # Note: the $$ is used to escape the $ for the import. In Grafana there is only one $.
          url: $${__value.raw}
          urlDisplayLabel: ""
    secureJsonData:
      tlsCACert: $__file{/certs/docker/rootCA.pem}
      tlsClientCert: $__file{/certs/docker/client.crt}
      tlsClientKey: $__file{/certs/docker/client.key}
    readOnly: false
    editable: true
  - uid: prometheus
    orgId: 1
    name: Prometheus
    type: prometheus
    typeName: Prometheus
    typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
    access: proxy
    url: https://prometheus:9090
    user: ""
    database: ""
    basicAuth: false
    isDefault: true
    jsonData:
      serverName: prometheus
      tlsAuth: true
      tlsAuthWithCACert: true
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: trace_id
      httpMethod: POST
    secureJsonData:
      tlsCACert: $__file{/certs/docker/rootCA.pem}
      tlsClientCert: $__file{/certs/docker/client.crt}
      tlsClientKey: $__file{/certs/docker/client.key}
    readOnly: false
    editable: true
  - uid: tempo
    orgId: 1
    name: Tempo
    type: tempo
    typeName: Tempo
    typeLogoUrl: public/app/plugins/datasource/tempo/img/tempo_logo.svg
    access: proxy
    url: https://tempo:3200
    user: ""
    database: ""
    basicAuth: false
    isDefault: false
    jsonData:
      serverName: tempo
      tlsAuth: true
      tlsAuthWithCACert: true
      nodeGraph:
        enabled: true
      search:
        hide: false
      streamingEnabled:
        metrics: true
        search: true
      tracesToLogsV2:
        customQuery: true
        datasourceUid: loki
        filterBySpanID: false
        filterByTraceID: false
        # Note: the $$ is used to escape the $ for the import. In Grafana there is only one $.
        query: '{$${__tags}} |  trace_id="$${__trace.traceId}"'
    secureJsonData:
      tlsCACert: $__file{/certs/docker/rootCA.pem}
      tlsClientCert: $__file{/certs/docker/client.crt}
      tlsClientKey: $__file{/certs/docker/client.key}
    readOnly: false
    editable: true
