name: Release with goreleaser
on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Unshallow Fetch
        run: git fetch --prune --unshallow

      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: release-drafter/release-drafter@v5
        id: rd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: prepare changlog
        run: |
          echo "${{ steps.rd.outputs.body }}" > "${{ runner.temp }}/CHANGELOG.md"

      - name: Release via goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --release-notes="${{ runner.temp }}/CHANGELOG.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # Note: The standard setting for the repository doesn't allow the default GITHUB_TOKEN to be used here
        # You have the following options:
        # - define the required permission in this job (see above)
        # - define a separate Personal Access Token
        # - or permit the default GITHUB_TOKEN read/write access
        #   see section "Workflow permissions" on https://github.com/mpapenbr/otlpdemo/settings/actions
